// ─────────────────────────────────────────────────────────────────────────────
// All the settings for the Housing Handbook Assistant live in this file.
// If you need to tune something, start here.
// ─────────────────────────────────────────────────────────────────────────────

export const CONFIG = {
  // Name shown on every citation. Update this when a new handbook is loaded.
  handbookTitle: "2026-27 On-Campus Housing Handbook",

  // The PDF that is the single source of truth. `npm run ingest` reads this.
  handbookPdfPath: "Digital 2026-27 Housing Handbook.pdf",

  // Where the split-up handbook is saved (generated by `npm run ingest`).
  indexPath: "data/handbook-index.json",

  // ── Model settings (Claude API) ───────────────────────────────────────────
  // Claude Haiku 4.5 handles both the safety classifier and the answers.
  chatModel: process.env.CHAT_MODEL || "claude-haiku-4-5-20251001",
  // GUARDRAIL #1: temperature is locked to 0 for every model call. Do not change this.
  temperature: 0 as const,
  maxAnswerTokens: 1024,
  // How long the safety classifier gets before we give up and escalate (fail closed).
  classifierTimeoutMs: 8000,
  // How much of the recent conversation to send along, so follow-up
  // questions like "what about weekends?" make sense. Kept small so each
  // question can only cost so much.
  historyTurns: 4,
  maxHistoryTurnLength: 600, // characters; longer turns are cut short

  // ── Cost and abuse limits (see lib/limits.ts) ────────────────────────────
  maxQuestionLength: 500,
  limits: {
    perVisitorPerMinute: 6, // questions per visitor per minute
    perVisitorPerDay: 40, // questions per visitor per day
    sitePerMinute: 40, // questions per minute across EVERYONE (stops bot swarms)
    // Hard cap on Claude spending per day (Michigan time). About $15/month.
    // When it's reached, AI answers pause until midnight; help screens still work.
    dailyBudgetUsd: Number(process.env.DAILY_BUDGET_USD) || 0.5,
  },
  // Claude Haiku 4.5 prices, used to add up the daily budget. Check
  // https://claude.com/pricing if you change models.
  pricePerMillionTokens: {
    input: 1.0,
    output: 5.0,
    cacheWrite: 2.0, // 1-hour cache writes cost 2x input
    cacheRead: 0.1,
  },
} as const;
