// ─────────────────────────────────────────────────────────────────────────────
// All the settings for the Ask Sparty live in this file.
// If you need to tune something, start here.
// ─────────────────────────────────────────────────────────────────────────────

export const CONFIG = {
  // Name shown on every citation. Update this when a new handbook is loaded.
  handbookTitle: "2026-27 On-Campus Housing Handbook",

  // The PDF that is the single source of truth. `npm run ingest` reads this.
  handbookPdfPath: "Digital 2026-27 Housing Handbook.pdf",

  // Where residents are sent to read the handbook itself. Answers link to a specific page with #page=N.
  // This is our copy of the 2026-27 PDF (public/handbook.pdf). If MSU publishes the 2026-27 file at an
  // official address, put that address here instead.
  handbookUrl: "/handbook.pdf",

  // Where the split-up handbook is saved (generated by `npm run ingest`).
  indexPath: "data/handbook-index.json",

  // ── Model settings (Claude API) ───────────────────────────────────────────
  // Claude Haiku 4.5 handles both the safety classifier and the answers.
  chatModel: process.env.CHAT_MODEL || "claude-haiku-4-5-20251001",
  // GUARDRAIL #1: temperature is locked to 0 for every model call. Do not change this.
  temperature: 0 as const,
  maxAnswerTokens: 1024,
  // How long the safety classifier gets before we give up and escalate (fail closed).
  classifierTimeoutMs: 8000,
  // How much of the recent conversation to send along, so follow-up
  // questions like "what about weekends?" make sense. Kept small so each
  // question can only cost so much.
  historyTurns: 4,
  maxHistoryTurnLength: 600, // characters; longer turns are cut short

  // ── RA on duty hours (Michigan time). RAs are on duty from 7 pm to 7 am. ──
  raOnDuty: {
    startHour: 19, // 7 pm
    endHour: 7, // 7 am
    hoursLabel: "7 pm to 7 am",
    timeZone: "America/Detroit",
  },

  // ── Dining skill (see lib/skills/dining/) ─────────────────────────────────
  dining: {
    // OFF until the menu source is authorized and the dining eval has passed.
    // Turn on by setting DINING_ENABLED=1 (in .env.local or Vercel).
    enabled: process.env.DINING_ENABLED === "1",
    defaultHallId: "south-pointe-at-case", // v1 covers Case Hall only
    cacheDays: 10, // how long a day's menu stays in the cache
    // Used only to guess which meal someone means when they don't say. These are
    // rough, not real serving hours (we don't have those yet).
    mealCutoffs: { breakfastUntil: 10.5, lunchUntil: 15 }, // hours in Michigan time (10.5 = 10:30 a.m.)
  },

  // ── Events skill (see lib/skills/events/) ────────────────────────────────
  events: {
    // OFF until the daily feed job is set up and the events eval has passed.
    // Turn on by setting EVENTS_ENABLED=1 (in .env.local or Vercel).
    enabled: process.env.EVENTS_ENABLED === "1",
    // UAB (MSU University Activities Board) publishes this RSS feed for programs to read.
    feedUrl: "https://uabevents.com/calendar/rss.xml",
    siteUrl: "https://uabevents.com/",
    cacheDays: 3, // how long the saved calendar is kept if the daily job stops working
    maxStaleHours: 48, // older than this and the bot says it doesn't have a current calendar
    maxEventsInAnswer: 6,
  },

  // ── Cost and abuse limits (see lib/limits.ts) ────────────────────────────
  maxQuestionLength: 500,
  limits: {
    perVisitorPerMinute: 6, // questions per visitor per minute
    perVisitorPerDay: 40, // questions per visitor per day
    sitePerMinute: 40, // questions per minute across EVERYONE (stops bot swarms)
    // Hard cap on Claude spending per day (Michigan time). About $15/month.
    // When it's reached, AI answers pause until midnight; help screens still work.
    dailyBudgetUsd: Number(process.env.DAILY_BUDGET_USD) || 0.5,
  },
  // Claude Haiku 4.5 prices, used to add up the daily budget. Check
  // https://claude.com/pricing if you change models.
  pricePerMillionTokens: {
    input: 1.0,
    output: 5.0,
    cacheWrite: 2.0, // 1-hour cache writes cost 2x input
    cacheRead: 0.1,
  },
} as const;
